### ISSUE TITLE
Calendar.js

### ISSUE THREAD

**Issue by osmanidik** [tarihvefelsefe/tarihvefelsefe.github.io#2]
Write a script that produces a calendar element.

Calendar must support:
- [ ] Start-end dates (days outside of the set range must be darker colour)
- [ ] Custom title
- [ ] Custom size (Scalable, responsive)
- [ ] Tooltip on hovering a day
- [ ] Looks good on chrome, firefox, safari, on desktop, android, ios!

**Comment by aaru15sharma** [comment]
can you assign this issue to me?
